# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='messenger',
  syntax='proto3',
  serialized_pb=_b('\n\x0fmessenger.proto\x12\tmessenger\"3\n\x07Message\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"\x16\n\x05\x42lank\x12\r\n\x05group\x18\x01 \x01(\t2\xb1\x01\n\tMessenger\x12\x39\n\rAuthUserGroup\x12\x12.messenger.Message\x1a\x12.messenger.Message\"\x00\x12\x36\n\nReceiveMsg\x12\x10.messenger.Blank\x1a\x12.messenger.Message\"\x00\x30\x01\x12\x31\n\x07SendMsg\x12\x12.messenger.Message\x1a\x10.messenger.Blank\"\x00\x42>\n#edu.sjsu.cmpe273.fall18.assignment1B\x0eMessengerProtoP\x01\xa2\x02\x04MSGRb\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='messenger.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='messenger.Message.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group', full_name='messenger.Message.group', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='messenger.Message.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)


_BLANK = _descriptor.Descriptor(
  name='Blank',
  full_name='messenger.Blank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='messenger.Blank.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Blank'] = _BLANK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.Message)
  ))
_sym_db.RegisterMessage(Message)

Blank = _reflection.GeneratedProtocolMessageType('Blank', (_message.Message,), dict(
  DESCRIPTOR = _BLANK,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.Blank)
  ))
_sym_db.RegisterMessage(Blank)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#edu.sjsu.cmpe273.fall18.assignment1B\016MessengerProtoP\001\242\002\004MSGR'))

_MESSENGER = _descriptor.ServiceDescriptor(
  name='Messenger',
  full_name='messenger.Messenger',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=108,
  serialized_end=285,
  methods=[
  _descriptor.MethodDescriptor(
    name='AuthUserGroup',
    full_name='messenger.Messenger.AuthUserGroup',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveMsg',
    full_name='messenger.Messenger.ReceiveMsg',
    index=1,
    containing_service=None,
    input_type=_BLANK,
    output_type=_MESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendMsg',
    full_name='messenger.Messenger.SendMsg',
    index=2,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_BLANK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGER)

DESCRIPTOR.services_by_name['Messenger'] = _MESSENGER

# @@protoc_insertion_point(module_scope)
